### PR TITLE
feat: webpack 5 support

### PR DESCRIPTION
**Pull request by DylanPiercey**
BREAKING CHANGE: Drop support for webpack 4

## Description

Adds support for webpack 5

## Checklist:

- [ ] I have updated/added documentation affected by my changes.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by xtremespb** [comment]
Any news on this PR?

**Comment by DylanPiercey** [comment]
@xtremespb this is in a prerelease of `@marko/webpack@7.0.0-1`. Likely to do an actual release sometime today or tomorrow.

**Comment by xtremespb** [comment]
Hi @DylanPiercey, do you have any news on Webpack 5 support?

**Comment by DylanPiercey** [comment]
@xtremespb I believe I fixed most of the issues in this PR to the point that it works with webpack 5. However it does not support the FS based cache which is something I'm most interested in seeing. Part of the change to support that needs to happen here and should not be too bad, however we also use another webpack module which does not support this (https://github.com/sysgears/webpack-virtual-modules/issues/76). We'll need to find a work around for that.

**Comment by non25** [comment]
@DylanPiercey maybe you will find this approach helpful: https://github.com/sveltejs/svelte-loader/pull/151

**Comment by DylanPiercey** [comment]
@non25 the link is helpful. It's actually somewhat similar to what we were doing in the past.

The problem is though that `@marko/webpack/plugin` also uses the virtual modules for Inlining an ever-changing manifest that maps the assets from the client compiler to the server compiler. I'm not really sure what the best approach to fixing that without virtual modules is.

**Comment by DylanPiercey** [comment]
This has been superseded by https://github.com/marko-js/webpack/pull/48.

**Pull request closed without merging**
